# Generated by Django 5.2.1 on 2025-05-08 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proizvoditel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('lokacija', models.CharField(max_length=50)),
                ('opis', models.CharField(max_length=200)),
                ('datum_osnovanje', models.DateField()),
                ('vo_eu', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MobilenUred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('tip', models.CharField(choices=[('S', 'Small'), ('M', 'Medium '), ('L', 'Large')], max_length=1)),
                ('slika', models.ImageField(blank=True, null=True, upload_to='phone_photos/')),
                ('cena', models.IntegerField()),
                ('godina_proizvodstvo', models.IntegerField()),
                ('nov', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proizvoditel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phoneShop.proizvoditel')),
            ],
        ),
    ]
