# Generated by Django 5.0.7 on 2025-05-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('slika', models.ImageField(blank=True, null=True, upload_to='suplement_photos/')),
                ('shifra', models.CharField(max_length=50)),
                ('proizvoditel', models.CharField(max_length=50)),
                ('dostapnost', models.BooleanField()),
                ('kategorija', models.CharField(choices=[('p', 'proteins'), ('v', 'vitamins'), ('c', 'creatines'), ('a', 'amino acids'), ('w', 'pre-workout ')], max_length=1)),
                ('cena', models.IntegerField()),
            ],
        ),
    ]
